include:
  - app-services.yml

services:
  powersync:
    depends_on:
      postgres:
        condition: service_healthy
      postgres-storage:
        condition: service_healthy
    container_name: goweb-powersync-service
    image: journeyapps/powersync-service:latest
    command: ["start", "-r", "unified"]
    volumes:
      - ./config:/config
    environment:
      - POWERSYNC_CONFIG_PATH=/config/powersync.yml
      - PS_DATA_SOURCE_URI=${PS_DATA_SOURCE_URI}
      - PS_STORAGE_SOURCE_URI=${PS_STORAGE_SOURCE_URI}
      - PS_PORT=${PS_PORT}
    ports:
      - "${PS_PORT}:${PS_PORT}"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    name: app-network
    driver: bridge