#!/bin/bash
source .env

export DATABASE_URL=$APP_DB_URI
export SERVER_PORT=$SERVER_PORT
export POWERSYNC_JWKS_PUBLIC_KEY=$DEMO_JWKS_PUBLIC_KEY
export POWERSYNC_JWKS_PRIVATE_KEY=$DEMO_JWKS_PRIVATE_KEY

go run main.go
